version: '3.8'

services:
  # The FastAPI Backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy

  # The MySQL Database
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - ./backend/.env
    environment:
      MYSQL_DATABASE: meditrack
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
